### ISSUE TITLE
JSON cannot be pasted into keyboard-layout-editor.com (KLE)

### ISSUE THREAD

**Issue by equalunique** [Lenbok/scad-keyboard-cases#1]
This might be a KLE problem, but FYI:

The kle-examples/*.json files don't render when pasted directly into KLE. I was able to get it working by removing the opening & closing square brackets, using a tool to remove all the line breaks, then re-insert new line breaks for each row. The Reddox layout also required some extra work for some character escaping issues with JSON syntax. Even though these modifications allow the layouts to be rendered in KLE, some of the legends being shown are odd.

The corrections I made are here: https://github.com/Lenbok/scad-redox-case/blob/master/kle-examples/redox-layout.json

Perhaps it would help if the links to the original KLE layouts were provided in the main readme and/or a readme inside scad-redox-case/kle-examples? :)

**Comment by Lenbok** [comment]
KLE doesn't supports directly pasting the full JSON data in like you did, as you discovered.  You have to click the "Upload JSON" button. If you do it that way it handles the example json files just fine (including the redox one).

I agree it would have been nice to record the source of the original KLE files, but at this point I'm not actually sure where I got some of those ones. The redox is one that I created myself, as the other redox one I found didn't have quite correct placement of some of the angled buttons (would have been fine for visualizing a layout, but not using as the basis for coordinates for making an actual keyboard case).
