### ISSUE TITLE
Mirrored crkbd top

### ISSUE THREAD

**Issue by saesh** [Lenbok/scad-keyboard-cases#2]
More a question than an issue. The crkbd files include the left side of the case. What software can I use to make a mirrored version for the right side? I want to get this case printed using an online service and they require all files ready.

Thanks!

**Comment by Lenbok** [comment]
@saesh I usually mirror in my slicing tool (e.g. slic3r) before printing. Slic3r does let you save the STL after you've transformed it, so that may be an easy way to go for you.

**Comment by saesh** [comment]
Thanks for the tip, I'll check Slic3r!
